// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvG1DFBFyYIrDkQXtU4hkbzI0ux_ndGoI',
    appId: '1:46523604116:web:24b4c0f1ad8fe78e562881',
    messagingSenderId: '46523604116',
    projectId: 'chat-app-f-d9f17',
    authDomain: 'chat-app-f-d9f17.firebaseapp.com',
    storageBucket: 'chat-app-f-d9f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkCsNNk5aibn8YHtJcjDjv24SoBEipBh4',
    appId: '1:46523604116:android:78d91b6e07889395562881',
    messagingSenderId: '46523604116',
    projectId: 'chat-app-f-d9f17',
    storageBucket: 'chat-app-f-d9f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fej0bmkqLPeg2EXTOfaqxpttz6AJwx0',
    appId: '1:46523604116:ios:5e5c28d6fd8e10c8562881',
    messagingSenderId: '46523604116',
    projectId: 'chat-app-f-d9f17',
    storageBucket: 'chat-app-f-d9f17.appspot.com',
    iosBundleId: 'com.flutter.chatAppf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7fej0bmkqLPeg2EXTOfaqxpttz6AJwx0',
    appId: '1:46523604116:ios:3bb5a837c4042f68562881',
    messagingSenderId: '46523604116',
    projectId: 'chat-app-f-d9f17',
    storageBucket: 'chat-app-f-d9f17.appspot.com',
    iosBundleId: 'com.flutter.chatAppf.RunnerTests',
  );
}
